### ISSUE TITLE
Packer tries to update twice with "-Su --aur"

### ISSUE THREAD

**Issue by bjauy** [gavinhungry/packer#6]
The aforementioned switch seems to do its job - the packages are updated. Its getting a bit weird after that:

    local database is up to date
    warning: android-sdk-platform-tools-r22-3 is up to date -- reinstalling
    [...]
    
    AUR (18): android-sdk-platform-tools...
    
    Proceed with installation? [Y/n]

The list of packages to reinstall is repeated three times.

Is there any other switch that should be used in this case?

**Comment by gavinhungry** [comment]
Hmm, I wonder how I never noticed this before. Is this new behavior?

I got this this morning:

```
(1/1) upgrading thinkfan                                     [################################] 100%
[...]

 local database is up to date
warning: thinkfan-0.9.2-3 is up to date -- reinstalling
warning: thinkfan-0.9.2-3 is up to date -- reinstalling
warning: thinkfan-0.9.2-3 is up to date -- reinstalling

AUR (1): thinkfan

Proceed with installation? [Y/n] 
```

Weird! I'll look into it.

**Comment by bjauy** [comment]
I have no idea when it could have happened. 

I switched to your fork on one of machines long time ago but haven't been updating AUR packages very often (and explicitly using ```-S <package_name>```). I've made the switch recently on other one where I'm more used to keep both types of packages up to date and there I've noticed this behavior.

I've also tried ```--noconfirm``` - packer exits after finishing its second round so at least it doesn't fall into infinite loop.

**Comment by gavinhungry** [comment]
I introduced this bug in April with this commit:
https://github.com/gavinhungry/packer/commit/f9a533965a4adcaf673f0079920b1d709f7fd158

The second block there adds another call to `installhandling`, without `exit`ing after the one above.

**Comment by gavinhungry** [comment]
I think https://github.com/gavinhungry/packer/commit/ec99348ef7305b29e53d976b27ab0bd29e85a4e4 fixes the issue, let me know!

**Comment by bjauy** [comment]
Yes, looks like it's fixed. Thank you!
