### ISSUE TITLE
Popularity wrongly set

### ISSUE THREAD

**Issue by jristz** [gavinhungry/packer#9]
I get errors when I search with “packer -Ss”.
´´´
packer -Ssa voxelands
/usr/bin/packer: line 799: printf: 1.8480890000000001: invalid number
aur/voxelands 1508.01-1 (10) (0,00) 
/usr/bin/packer: line 799: printf: 1.4361269999999999: invalid number
    A fork of Minetest, an Infiniminer/Minecraft inspired game
´´´
Something is wrong with the popularity, also is spected a max of 6 points

**Comment by gavinhungry** [comment]
I get:

```
$ packer -Ssa voxelands

aur/voxelands 1508.01-1 (10) (1.82) 
    A fork of Minetest, an Infiniminer/Minecraft inspired game
aur/voxelands-bin 1508.01-1 (2) (1.42) 
    A fork of Minetest, an Infiniminer/Minecraft inspired game
aur/voxelands-next-git v1508.01.r0.gfa519de-1 (2) (0.00) 
    A fork of Minetest, an Infiniminer/Minecraft inspired game (experimental branch)
```

**Comment by gavinhungry** [comment]
Assuming you installed this via [packer-git](https://aur.archlinux.org/packages/packer-git/) on the AUR, are you on `308.700e9e3-1`?

**Comment by gavinhungry** [comment]
@jristz, this may just be a locale issue. Can you try the following?

    printf "%.2f" 1.12345

and

    LC_NUMERIC=C printf "%.2f" 1.12345

**Comment by jristz** [comment]
First give me invalid number, the second work ok.
In my locale (and ISO correctness langs were english is not one) we use an
, as  float separator.

**Comment by gavinhungry** [comment]
Should be fixed in `309.a203a60-1` then! :)
